packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@sentry/cli': false
  '@swc/core': true
  cbor-extract: false
  'esbuild': true
  'prisma': true
  'sharp': true
  'unrs-resolver': true

overrides:
  'nanoid@<3.3.17': 3.3.17
  'nanoid@>=4.0.0 <5.1.16': 5.1.16
  postcss: 8.5.23
  sharp: 0.35.3
  typescript: 5.9.3
  'undici@<7.29.0': 7.29.0
