import { createHash } from 'node:crypto';
import { resources } from './config';
import { resourceSiteAt } from './resource-sites';
import type { KingdomsWorld } from './types';
import { abandonedRegions, type AbandonedVillage } from './abandoned-village-types';
import {
  ABANDONED_RESOURCE_CAPACITY,
  ABANDONED_VILLAGE_COUNT,
  abandonedLayout,
  assertAbandonedPreviewWorldId,
} from './abandoned-villages';
import {
  ABANDONED_PLAYER_SEPARATION_KM,
  ABANDONED_SITE_SEPARATION_KM,
  geographicDistanceKm,
  type AbandonedPlacementDomain,
  type GeographicPoint,
} from './abandoned-village-geography';

const MAX_ATTEMPTS = 20000;
const regionNames = { egypt: 'مصر', levant: 'الشام', iraq: 'العراق', arabia: 'الجزيرة العربية' };

function randomFor(seed: string, worldId: string) {
  const digest = createHash('sha256').update(`${worldId}:${seed}`).digest();
  let value = digest.readUInt32BE(0);
  // Fixed PRNG version; actual coordinates are stored and never regenerated by reads.
  return () => {
    value = (value + 0x6d2b79f5) >>> 0;
    let bits = Math.imul(value ^ (value >>> 15), 1 | value);
    bits ^= bits + Math.imul(bits ^ (bits >>> 7), 61 | bits);
    return ((bits ^ (bits >>> 14)) >>> 0) / 4294967296;
  };
}

/** Opt-in construction for preview_* worlds only. No production route calls this function. */
export function withAbandonedPreviewVillages(
  world: KingdomsWorld,
  worldId: string,
  seed: string,
  domain: AbandonedPlacementDomain,
  playerLocations: readonly GeographicPoint[] = [],
): KingdomsWorld {
  assertAbandonedPreviewWorldId(worldId);
  return withAbandonedVillages(world, worldId, seed, domain, playerLocations, 'isolated-preview');
}

/** Explicit provisioning only: callers lock one selected world; reads never generate a layout. */
export function withAbandonedVillages(
  world: KingdomsWorld,
  worldId: string,
  seed: string,
  domain: AbandonedPlacementDomain,
  playerLocations: readonly GeographicPoint[],
  scope: 'isolated-preview' | 'kingdom-world',
  generatedAt = world.updatedAt,
): KingdomsWorld {
  if (scope === 'isolated-preview') assertAbandonedPreviewWorldId(worldId);
  else if (!/^kw_[a-zA-Z0-9_-]{1,97}$/.test(worldId)) throw new Error('Invalid kingdom world id');
  if (abandonedLayout(world, worldId)) return world;
  if (!/^[a-zA-Z0-9_-]{8,128}$/.test(seed)) throw new Error('Invalid preview layout seed');
  const random = randomFor(seed, worldId);
  const occupied = new Set([
    ...Object.values(world.villages).map((village) => `${village.x},${village.y}`),
    ...Object.keys(world.territories),
    ...world.movements.map((move) => `${move.targetX},${move.targetY}`),
  ]);
  const villages: Record<string, AbandonedVillage> = {};
  const radius =
    scope === 'kingdom-world' ? world.config.worldRadius : Math.min(24, world.config.worldRadius);
  const span = radius * 2 + 1;
  let attempts = 0;
  for (let index = 0; index < ABANDONED_VILLAGE_COUNT; index++) {
    const region =
      abandonedRegions[Math.floor(index / (ABANDONED_VILLAGE_COUNT / abandonedRegions.length))]!;
    let point: GeographicPoint | undefined;
    let countryCode = '';
    while (attempts++ < MAX_ATTEMPTS) {
      const candidate = {
        longitude: domain.bounds.west + random() * (domain.bounds.east - domain.bounds.west),
        // Uniform geographic area, rather than uniform latitude.
        latitude:
          (Math.asin(
            Math.sin((domain.bounds.south * Math.PI) / 180) +
              random() *
                (Math.sin((domain.bounds.north * Math.PI) / 180) -
                  Math.sin((domain.bounds.south * Math.PI) / 180)),
          ) *
            180) /
          Math.PI,
      };
      const rounded = {
        longitude: Number(candidate.longitude.toFixed(6)),
        latitude: Number(candidate.latitude.toFixed(6)),
      };
      const location = domain.locate(rounded, region);
      if (
        !location ||
        Object.values(villages).some(
          (site) => geographicDistanceKm(site, rounded) < ABANDONED_SITE_SEPARATION_KM,
        ) ||
        playerLocations.some(
          (player) => geographicDistanceKm(player, rounded) < ABANDONED_PLAYER_SEPARATION_KM,
        )
      )
        continue;
      point = rounded;
      countryCode = location.countryCode;
      break;
    }
    if (!point) throw new Error('تعذر توزيع القرى المهجورة داخل اليابسة ضمن ميزانية التوليد');
    let cell: { x: number; y: number } | undefined;
    let bestSpread = -1;
    let candidates = 0;
    while (attempts++ < MAX_ATTEMPTS) {
      const x = Math.floor(random() * span) - radius,
        y = Math.floor(random() * span) - radius;
      const key = `${x},${y}`;
      if (occupied.has(key) || resourceSiteAt(world.config.worldRadius, x, y)) continue;
      const spread = Math.min(
        ...Object.values(villages).map((site) => Math.hypot(site.x - x, site.y - y)),
        radius * 2,
      );
      if (scope === 'kingdom-world') {
        if (
          Object.values(world.villages).some((home) => Math.hypot(home.x - x, home.y - y) < 2) ||
          spread < 3
        )
          continue;
        if (spread > bestSpread) {
          cell = { x, y };
          bestSpread = spread;
        }
        if (++candidates < 32) continue;
        break;
      }
      cell = { x, y };
      break;
    }
    if (!cell) throw new Error('تعذر حجز خانات اللعب للقرى المهجورة');
    occupied.add(`${cell.x},${cell.y}`);
    const id = `av_${createHash('sha256').update(`${worldId}:${seed}:${index}`).digest('hex').slice(0, 20)}`;
    const cap = ABANDONED_RESOURCE_CAPACITY;
    villages[id] = {
      id,
      name: `قرية مهجورة · ${regionNames[region]} ${(index % 12) + 1}`,
      region,
      countryCode,
      ...point,
      ...cell,
      stock: resources(cap, cap, cap, cap, cap),
      stockUpdatedAt: generatedAt,
    };
  }
  return {
    ...world,
    abandonedVillages: {
      version: 1,
      scope,
      worldId,
      seed,
      domainVersion: domain.version,
      generatedAt,
      villages,
    },
  };
}
